[package]
name = "opencoders"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
reqwest = "0.12"
tokio = { version = "1", features = ["full"] }

# # For serializing/deserializing JSON data for the API
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"

# # Optional, but recommended for handling errors gracefully
# anyhow = "1.0"
