/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiAuth {
    #[serde(rename = "key")]
    pub key: String,
}

impl ApiAuth {
    pub fn new(_type: Type, key: String) -> ApiAuth {
        ApiAuth { key }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "api")]
    Api,
}

impl Default for Type {
    fn default() -> Type {
        Self::Api
    }
}
