/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct App {
    #[serde(rename = "hostname")]
    pub hostname: String,
    #[serde(rename = "git")]
    pub git: bool,
    #[serde(rename = "path")]
    pub path: Box<models::AppPath>,
    #[serde(rename = "time")]
    pub time: Box<models::AppTime>,
}

impl App {
    pub fn new(hostname: String, git: bool, path: models::AppPath, time: models::AppTime) -> App {
        App {
            hostname,
            git,
            path: Box::new(path),
            time: Box::new(time),
        }
    }
}

