/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppTime {
    #[serde(rename = "initialized", skip_serializing_if = "Option::is_none")]
    pub initialized: Option<f64>,
}

impl AppTime {
    pub fn new() -> AppTime {
        AppTime {
            initialized: None,
        }
    }
}

