/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "name")]
pub enum AssistantMessageError {
    #[serde(rename = "ProviderAuthError")]
    ProviderAuthError(Box<models::ProviderAuthError>),
    #[serde(rename = "UnknownError")]
    UnknownError(Box<models::UnknownError>),
    #[serde(rename = "MessageOutputLengthError")]
    MessageOutputLengthError(Box<models::MessageOutputLengthError>),
    #[serde(rename = "MessageAbortedError")]
    MessageAbortedError(Box<models::MessageAbortedError>),
}

impl Default for AssistantMessageError {
    fn default() -> Self {
        Self::ProviderAuthError(Default::default())
    }
}
