/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Auth {
    #[serde(rename="oauth")]
    Oauth(Box<models::OAuth>),
    #[serde(rename="api")]
    Api(Box<models::ApiAuth>),
    #[serde(rename="wellknown")]
    Wellknown(Box<models::WellKnownAuth>),
}

impl Default for Auth {
    fn default() -> Self {
        Self::Oauth(Default::default())
    }
}


