/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigPermission {
    #[serde(rename = "edit", skip_serializing_if = "Option::is_none")]
    pub edit: Option<Box<models::ConfigPermissionEdit>>,
    #[serde(rename = "bash", skip_serializing_if = "Option::is_none")]
    pub bash: Option<Box<models::ConfigPermissionBash>>,
    #[serde(rename = "webfetch", skip_serializing_if = "Option::is_none")]
    pub webfetch: Option<Box<models::ConfigPermissionEdit>>,
}

impl ConfigPermission {
    pub fn new() -> ConfigPermission {
        ConfigPermission {
            edit: None,
            bash: None,
            webfetch: None,
        }
    }
}

