/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigExperimental {
    #[serde(rename = "hook", skip_serializing_if = "Option::is_none")]
    pub hook: Option<Box<models::ConfigExperimentalHook>>,
}

impl ConfigExperimental {
    pub fn new() -> ConfigExperimental {
        ConfigExperimental {
            hook: None,
        }
    }
}

