/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigLspValueAnyOf {
    #[serde(rename = "disabled")]
    pub disabled: bool,
}

impl ConfigLspValueAnyOf {
    pub fn new(disabled: bool) -> ConfigLspValueAnyOf {
        ConfigLspValueAnyOf {
            disabled,
        }
    }
}

