/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigTui : TUI specific settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTui {
    /// TUI scroll speed
    #[serde(rename = "scroll_speed")]
    pub scroll_speed: f64,
}

impl ConfigTui {
    /// TUI specific settings
    pub fn new(scroll_speed: f64) -> ConfigTui {
        ConfigTui {
            scroll_speed,
        }
    }
}

