/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigMode : Modes configuration, see https://opencode.ai/docs/modes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigMode {
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<Box<models::ModeConfig>>,
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<Box<models::ModeConfig>>,
}

impl ConfigMode {
    /// Modes configuration, see https://opencode.ai/docs/modes
    pub fn new() -> ConfigMode {
        ConfigMode {
            build: None,
            plan: None,
        }
    }
}

