/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPeriodInstallationPeriodUpdated {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventInstallationUpdatedProperties>,
}

impl EventPeriodInstallationPeriodUpdated {
    pub fn new(r#type: String, properties: models::EventInstallationUpdatedProperties) -> EventPeriodInstallationPeriodUpdated {
        EventPeriodInstallationPeriodUpdated {
            r#type,
            properties: Box::new(properties),
        }
    }
}

