/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Event {
    #[serde(rename="lsp.client.diagnostics")]
    LspPeriodClientPeriodDiagnostics(Box<models::EventPeriodLspPeriodClientPeriodDiagnostics>),
    #[serde(rename="permission.updated")]
    PermissionPeriodUpdated(Box<models::EventPeriodPermissionPeriodUpdated>),
    #[serde(rename="file.edited")]
    FilePeriodEdited(Box<models::EventPeriodFilePeriodEdited>),
    #[serde(rename="installation.updated")]
    InstallationPeriodUpdated(Box<models::EventPeriodInstallationPeriodUpdated>),
    #[serde(rename="message.updated")]
    MessagePeriodUpdated(Box<models::EventPeriodMessagePeriodUpdated>),
    #[serde(rename="message.removed")]
    MessagePeriodRemoved(Box<models::EventPeriodMessagePeriodRemoved>),
    #[serde(rename="message.part.updated")]
    MessagePeriodPartPeriodUpdated(Box<models::EventPeriodMessagePeriodPartPeriodUpdated>),
    #[serde(rename="storage.write")]
    StoragePeriodWrite(Box<models::EventPeriodStoragePeriodWrite>),
    #[serde(rename="session.updated")]
    SessionPeriodUpdated(Box<models::EventPeriodSessionPeriodUpdated>),
    #[serde(rename="session.deleted")]
    SessionPeriodDeleted(Box<models::EventPeriodSessionPeriodDeleted>),
    #[serde(rename="session.idle")]
    SessionPeriodIdle(Box<models::EventPeriodSessionPeriodIdle>),
    #[serde(rename="session.error")]
    SessionPeriodError(Box<models::EventPeriodSessionPeriodError>),
    #[serde(rename="file.watcher.updated")]
    FilePeriodWatcherPeriodUpdated(Box<models::EventPeriodFilePeriodWatcherPeriodUpdated>),
    #[serde(rename="ide.installed")]
    IdePeriodInstalled(Box<models::EventPeriodIdePeriodInstalled>),
}

impl Default for Event {
    fn default() -> Self {
        Self::LspPeriodClientPeriodDiagnostics(Default::default())
    }
}


