/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPeriodSessionPeriodIdle {
    #[serde(rename = "properties")]
    pub properties: Box<models::EventSessionIdleProperties>,
}

impl EventPeriodSessionPeriodIdle {
    pub fn new(
        _type: Type,
        properties: models::EventSessionIdleProperties,
    ) -> EventPeriodSessionPeriodIdle {
        EventPeriodSessionPeriodIdle {
            properties: Box::new(properties),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "session.idle")]
    SessionPeriodIdle,
}

impl Default for Type {
    fn default() -> Type {
        Self::SessionPeriodIdle
    }
}
