/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPeriodMessagePeriodRemoved {
    #[serde(rename = "properties")]
    pub properties: Box<models::EventMessageRemovedProperties>,
}

impl EventPeriodMessagePeriodRemoved {
    pub fn new(
        _type: Type,
        properties: models::EventMessageRemovedProperties,
    ) -> EventPeriodMessagePeriodRemoved {
        EventPeriodMessagePeriodRemoved {
            properties: Box::new(properties),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "message.removed")]
    MessagePeriodRemoved,
}

impl Default for Type {
    fn default() -> Type {
        Self::MessagePeriodRemoved
    }
}
