/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPeriodPermissionPeriodUpdated {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::Permission>,
}

impl EventPeriodPermissionPeriodUpdated {
    pub fn new(r#type: Type, properties: models::Permission) -> EventPeriodPermissionPeriodUpdated {
        EventPeriodPermissionPeriodUpdated {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "permission.updated")]
    PermissionPeriodUpdated,
}

impl Default for Type {
    fn default() -> Type {
        Self::PermissionPeriodUpdated
    }
}

