/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventIdeInstalledProperties {
    #[serde(rename = "ide")]
    pub ide: String,
}

impl EventIdeInstalledProperties {
    pub fn new(ide: String) -> EventIdeInstalledProperties {
        EventIdeInstalledProperties {
            ide,
        }
    }
}

