/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPeriodMessagePeriodPartPeriodRemoved {
    #[serde(rename = "properties")]
    pub properties: Box<models::EventMessagePartRemovedProperties>,
}

impl EventPeriodMessagePeriodPartPeriodRemoved {
    pub fn new(
        _type: Type,
        properties: models::EventMessagePartRemovedProperties,
    ) -> EventPeriodMessagePeriodPartPeriodRemoved {
        EventPeriodMessagePeriodPartPeriodRemoved {
            properties: Box::new(properties),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "message.part.removed")]
    MessagePeriodPartPeriodRemoved,
}

impl Default for Type {
    fn default() -> Type {
        Self::MessagePeriodPartPeriodRemoved
    }
}
