/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPeriodSessionPeriodError {
    #[serde(rename = "properties")]
    pub properties: Box<models::EventSessionErrorProperties>,
}

impl EventPeriodSessionPeriodError {
    pub fn new(
        _type: Type,
        properties: models::EventSessionErrorProperties,
    ) -> EventPeriodSessionPeriodError {
        EventPeriodSessionPeriodError {
            properties: Box::new(properties),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "session.error")]
    SessionPeriodError,
}

impl Default for Type {
    fn default() -> Type {
        Self::SessionPeriodError
    }
}
