/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPeriodFilePeriodEdited {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventFileEditedProperties>,
}

impl EventPeriodFilePeriodEdited {
    pub fn new(r#type: Type, properties: models::EventFileEditedProperties) -> EventPeriodFilePeriodEdited {
        EventPeriodFilePeriodEdited {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file.edited")]
    FilePeriodEdited,
}

impl Default for Type {
    fn default() -> Type {
        Self::FilePeriodEdited
    }
}

