/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FilePartSource {
    #[serde(rename="file")]
    File(Box<models::FileSource>),
    #[serde(rename="symbol")]
    Symbol(Box<models::SymbolSource>),
}

impl Default for FilePartSource {
    fn default() -> Self {
        Self::File(Default::default())
    }
}


