/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilePart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "mime")]
    pub mime: String,
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "url")]
    pub url: String,
}

impl FilePart {
    pub fn new(id: String, session_id: String, message_id: String, r#type: String, mime: String, url: String) -> FilePart {
        FilePart {
            id,
            session_id,
            message_id,
            r#type,
            mime,
            filename: None,
            url,
        }
    }
}

