/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeybindsConfig {
    /// Leader key for keybind combinations
    #[serde(rename = "leader")]
    pub leader: String,
    /// Show help dialog
    #[serde(rename = "app_help")]
    pub app_help: String,
    /// Next mode
    #[serde(rename = "switch_mode")]
    pub switch_mode: String,
    /// Previous Mode
    #[serde(rename = "switch_mode_reverse")]
    pub switch_mode_reverse: String,
    /// Open external editor
    #[serde(rename = "editor_open")]
    pub editor_open: String,
    /// Export session to editor
    #[serde(rename = "session_export")]
    pub session_export: String,
    /// Create a new session
    #[serde(rename = "session_new")]
    pub session_new: String,
    /// List all sessions
    #[serde(rename = "session_list")]
    pub session_list: String,
    /// Share current session
    #[serde(rename = "session_share")]
    pub session_share: String,
    /// Unshare current session
    #[serde(rename = "session_unshare")]
    pub session_unshare: String,
    /// Interrupt current session
    #[serde(rename = "session_interrupt")]
    pub session_interrupt: String,
    /// Compact the session
    #[serde(rename = "session_compact")]
    pub session_compact: String,
    /// Toggle tool details
    #[serde(rename = "tool_details")]
    pub tool_details: String,
    /// List available models
    #[serde(rename = "model_list")]
    pub model_list: String,
    /// List available themes
    #[serde(rename = "theme_list")]
    pub theme_list: String,
    /// List files
    #[serde(rename = "file_list")]
    pub file_list: String,
    /// Close file
    #[serde(rename = "file_close")]
    pub file_close: String,
    /// Search file
    #[serde(rename = "file_search")]
    pub file_search: String,
    /// Split/unified diff
    #[serde(rename = "file_diff_toggle")]
    pub file_diff_toggle: String,
    /// Create/update AGENTS.md
    #[serde(rename = "project_init")]
    pub project_init: String,
    /// Clear input field
    #[serde(rename = "input_clear")]
    pub input_clear: String,
    /// Paste from clipboard
    #[serde(rename = "input_paste")]
    pub input_paste: String,
    /// Submit input
    #[serde(rename = "input_submit")]
    pub input_submit: String,
    /// Insert newline in input
    #[serde(rename = "input_newline")]
    pub input_newline: String,
    /// Scroll messages up by one page
    #[serde(rename = "messages_page_up")]
    pub messages_page_up: String,
    /// Scroll messages down by one page
    #[serde(rename = "messages_page_down")]
    pub messages_page_down: String,
    /// Scroll messages up by half page
    #[serde(rename = "messages_half_page_up")]
    pub messages_half_page_up: String,
    /// Scroll messages down by half page
    #[serde(rename = "messages_half_page_down")]
    pub messages_half_page_down: String,
    /// Navigate to previous message
    #[serde(rename = "messages_previous")]
    pub messages_previous: String,
    /// Navigate to next message
    #[serde(rename = "messages_next")]
    pub messages_next: String,
    /// Navigate to first message
    #[serde(rename = "messages_first")]
    pub messages_first: String,
    /// Navigate to last message
    #[serde(rename = "messages_last")]
    pub messages_last: String,
    /// Toggle layout
    #[serde(rename = "messages_layout_toggle")]
    pub messages_layout_toggle: String,
    /// Copy message
    #[serde(rename = "messages_copy")]
    pub messages_copy: String,
    /// Revert message
    #[serde(rename = "messages_revert")]
    pub messages_revert: String,
    /// Exit the application
    #[serde(rename = "app_exit")]
    pub app_exit: String,
}

impl KeybindsConfig {
    pub fn new(leader: String, app_help: String, switch_mode: String, switch_mode_reverse: String, editor_open: String, session_export: String, session_new: String, session_list: String, session_share: String, session_unshare: String, session_interrupt: String, session_compact: String, tool_details: String, model_list: String, theme_list: String, file_list: String, file_close: String, file_search: String, file_diff_toggle: String, project_init: String, input_clear: String, input_paste: String, input_submit: String, input_newline: String, messages_page_up: String, messages_page_down: String, messages_half_page_up: String, messages_half_page_down: String, messages_previous: String, messages_next: String, messages_first: String, messages_last: String, messages_layout_toggle: String, messages_copy: String, messages_revert: String, app_exit: String) -> KeybindsConfig {
        KeybindsConfig {
            leader,
            app_help,
            switch_mode,
            switch_mode_reverse,
            editor_open,
            session_export,
            session_new,
            session_list,
            session_share,
            session_unshare,
            session_interrupt,
            session_compact,
            tool_details,
            model_list,
            theme_list,
            file_list,
            file_close,
            file_search,
            file_diff_toggle,
            project_init,
            input_clear,
            input_paste,
            input_submit,
            input_newline,
            messages_page_up,
            messages_page_down,
            messages_half_page_up,
            messages_half_page_down,
            messages_previous,
            messages_next,
            messages_first,
            messages_last,
            messages_layout_toggle,
            messages_copy,
            messages_revert,
            app_exit,
        }
    }
}

