/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchSubmatchesInner {
    #[serde(rename = "match")]
    pub r#match: Box<models::MatchPath>,
    #[serde(rename = "start")]
    pub start: f64,
    #[serde(rename = "end")]
    pub end: f64,
}

impl MatchSubmatchesInner {
    pub fn new(r#match: models::MatchPath, start: f64, end: f64) -> MatchSubmatchesInner {
        MatchSubmatchesInner {
            r#match: Box::new(r#match),
            start,
            end,
        }
    }
}

