/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchPath {
    #[serde(rename = "text")]
    pub text: String,
}

impl MatchPath {
    pub fn new(text: String) -> MatchPath {
        MatchPath {
            text,
        }
    }
}

