/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpRemoteConfig {
    /// Type of MCP server connection
    #[serde(rename = "type")]
    pub r#type: String,
    /// URL of the remote MCP server
    #[serde(rename = "url")]
    pub url: String,
    /// Enable or disable the MCP server on startup
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Headers to send with the request
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
}

impl McpRemoteConfig {
    pub fn new(r#type: String, url: String) -> McpRemoteConfig {
        McpRemoteConfig {
            r#type,
            url,
            enabled: None,
            headers: None,
        }
    }
}

