/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpLocalConfig {
    /// Command and arguments to run the MCP server
    #[serde(rename = "command")]
    pub command: Vec<String>,
    /// Environment variables to set when running the MCP server
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<std::collections::HashMap<String, String>>,
    /// Enable or disable the MCP server on startup
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl McpLocalConfig {
    pub fn new(_type: String, command: Vec<String>) -> McpLocalConfig {
        McpLocalConfig {
            command,
            environment: None,
            enabled: None,
        }
    }
}
