/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Message {
    #[serde(rename = "user")]
    User(Box<models::UserMessage>),
    #[serde(rename = "assistant")]
    Assistant(Box<models::AssistantMessage>),
}

impl Default for Message {
    fn default() -> Self {
        Self::User(Default::default())
    }
}
