/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageAbortedError {
    #[serde(rename = "name")]
    pub name: Name,
    #[serde(rename = "data")]
    pub data: serde_json::Value,
}

impl MessageAbortedError {
    pub fn new(name: Name, data: serde_json::Value) -> MessageAbortedError {
        MessageAbortedError {
            name,
            data,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "MessageAbortedError")]
    MessageAbortedError,
}

impl Default for Name {
    fn default() -> Name {
        Self::MessageAbortedError
    }
}

