/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageOutputLengthError {
    #[serde(rename = "data")]
    pub data: serde_json::Value,
}

impl MessageOutputLengthError {
    pub fn new(_name: String, data: serde_json::Value) -> MessageOutputLengthError {
        MessageOutputLengthError { data }
    }
}
