/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageAbortedError {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "data")]
    pub data: serde_json::Value,
}

impl MessageAbortedError {
    pub fn new(name: String, data: serde_json::Value) -> MessageAbortedError {
        MessageAbortedError {
            name,
            data,
        }
    }
}

