/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelLimit {
    #[serde(rename = "context")]
    pub context: f64,
    #[serde(rename = "output")]
    pub output: f64,
}

impl ModelLimit {
    pub fn new(context: f64, output: f64) -> ModelLimit {
        ModelLimit {
            context,
            output,
        }
    }
}

