/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mode {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::ModeModel>>,
    #[serde(rename = "prompt", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    #[serde(rename = "tools")]
    pub tools: std::collections::HashMap<String, bool>,
}

impl Mode {
    pub fn new(name: String, tools: std::collections::HashMap<String, bool>) -> Mode {
        Mode {
            name,
            model: None,
            prompt: None,
            tools,
        }
    }
}

