/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Match {
    #[serde(rename = "path")]
    pub path: Box<models::PostTuiAppendPromptRequest>,
    #[serde(rename = "lines")]
    pub lines: Box<models::PostTuiAppendPromptRequest>,
    #[serde(rename = "line_number")]
    pub line_number: f64,
    #[serde(rename = "absolute_offset")]
    pub absolute_offset: f64,
    #[serde(rename = "submatches")]
    pub submatches: Vec<models::MatchSubmatchesInner>,
}

impl Match {
    pub fn new(path: models::PostTuiAppendPromptRequest, lines: models::PostTuiAppendPromptRequest, line_number: f64, absolute_offset: f64, submatches: Vec<models::MatchSubmatchesInner>) -> Match {
        Match {
            path: Box::new(path),
            lines: Box::new(lines),
            line_number,
            absolute_offset,
            submatches,
        }
    }
}

