/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth {
    #[serde(rename = "refresh")]
    pub refresh: String,
    #[serde(rename = "access")]
    pub access: String,
    #[serde(rename = "expires")]
    pub expires: f64,
}

impl OAuth {
    pub fn new(_type: Type, refresh: String, access: String, expires: f64) -> OAuth {
        OAuth {
            refresh,
            access,
            expires,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "oauth")]
    Oauth,
}

impl Default for Type {
    fn default() -> Type {
        Self::Oauth
    }
}
