/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PostSessionByIdMessageRequestPartsInner {
    #[serde(rename = "text")]
    Text(Box<models::TextPartInput>),
    #[serde(rename = "file")]
    File(Box<models::FilePartInput>),
}

impl Default for PostSessionByIdMessageRequestPartsInner {
    fn default() -> Self {
        Self::Text(Default::default())
    }
}
