/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostSessionByIdMessageRequest {
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "providerID")]
    pub provider_id: String,
    #[serde(rename = "modelID")]
    pub model_id: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "parts")]
    pub parts: Vec<models::PostSessionByIdMessageRequestPartsInner>,
}

impl PostSessionByIdMessageRequest {
    pub fn new(message_id: String, provider_id: String, model_id: String, mode: String, parts: Vec<models::PostSessionByIdMessageRequestPartsInner>) -> PostSessionByIdMessageRequest {
        PostSessionByIdMessageRequest {
            message_id,
            provider_id,
            model_id,
            mode,
            parts,
        }
    }
}

