/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionShellRequest {
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "command")]
    pub command: String,
}

impl SessionShellRequest {
    pub fn new(agent: String, command: String) -> SessionShellRequest {
        SessionShellRequest {
            agent,
            command,
        }
    }
}

