/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionInitRequest {
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "providerID")]
    pub provider_id: String,
    #[serde(rename = "modelID")]
    pub model_id: String,
}

impl SessionInitRequest {
    pub fn new(message_id: String, provider_id: String, model_id: String) -> SessionInitRequest {
        SessionInitRequest {
            message_id,
            provider_id,
            model_id,
        }
    }
}

