/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepFinishPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "cost")]
    pub cost: f64,
    #[serde(rename = "tokens")]
    pub tokens: Box<models::AssistantMessageTokens>,
}

impl StepFinishPart {
    pub fn new(
        id: String,
        session_id: String,
        message_id: String,
        _type: String,
        cost: f64,
        tokens: models::AssistantMessageTokens,
    ) -> StepFinishPart {
        StepFinishPart {
            id,
            session_id,
            message_id,
            cost,
            tokens: Box::new(tokens),
        }
    }
}
