/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "synthetic", skip_serializing_if = "Option::is_none")]
    pub synthetic: Option<bool>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<models::TextPartTime>>,
}

impl TextPart {
    pub fn new(
        id: String,
        session_id: String,
        message_id: String,
        _type: String,
        text: String,
    ) -> TextPart {
        TextPart {
            id,
            session_id,
            message_id,
            text,
            synthetic: None,
            time: None,
        }
    }
}
