/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum ToolState {
    #[serde(rename = "pending")]
    Pending(Box<models::ToolStatePending>),
    #[serde(rename = "running")]
    Running(Box<models::ToolStateRunning>),
    #[serde(rename = "completed")]
    Completed(Box<models::ToolStateCompleted>),
    #[serde(rename = "error")]
    Error(Box<models::ToolStateError>),
}

impl Default for ToolState {
    fn default() -> Self {
        Self::Pending(Default::default())
    }
}
