/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStateCompleted {
    #[serde(rename = "input")]
    pub input: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "output")]
    pub output: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "time")]
    pub time: Box<models::ToolStateCompletedTime>,
}

impl ToolStateCompleted {
    pub fn new(
        _status: String,
        input: std::collections::HashMap<String, serde_json::Value>,
        output: String,
        title: String,
        metadata: std::collections::HashMap<String, serde_json::Value>,
        time: models::ToolStateCompletedTime,
    ) -> ToolStateCompleted {
        ToolStateCompleted {
            input,
            output,
            title,
            metadata,
            time: Box::new(time),
        }
    }
}
