/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStateError {
    #[serde(rename = "input")]
    pub input: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "time")]
    pub time: Box<models::ToolStateCompletedTime>,
}

impl ToolStateError {
    pub fn new(
        _status: String,
        input: std::collections::HashMap<String, serde_json::Value>,
        error: String,
        time: models::ToolStateCompletedTime,
    ) -> ToolStateError {
        ToolStateError {
            input,
            error,
            time: Box::new(time),
        }
    }
}
