/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnknownError {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "data")]
    pub data: Box<models::UnknownErrorData>,
}

impl UnknownError {
    pub fn new(name: String, data: models::UnknownErrorData) -> UnknownError {
        UnknownError {
            name,
            data: Box::new(data),
        }
    }
}

