/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnknownError {
    #[serde(rename = "data")]
    pub data: Box<models::UnknownErrorData>,
}

impl UnknownError {
    pub fn new(_name: Name, data: models::UnknownErrorData) -> UnknownError {
        UnknownError {
            data: Box::new(data),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "UnknownError")]
    UnknownError,
}

impl Default for Name {
    fn default() -> Name {
        Self::UnknownError
    }
}
