/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WellKnownAuth {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl WellKnownAuth {
    pub fn new(_type: Type, key: String, token: String) -> WellKnownAuth {
        WellKnownAuth { key, token }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "wellknown")]
    Wellknown,
}

impl Default for Type {
    fn default() -> Type {
        Self::Wellknown
    }
}
